version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
      - "53:53"
    environment:
      OLLAMA_KEEP_ALIVE: "24h"
      OLLAMA_HOST: "0.0.0.0"
      OLLAMA_ORIGINS: "http://localhost,https://localhost,http://127.0.0.1,https://127.0.0.1,http://0.0.0.0,https://0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - yan
    labels:
      deunhealth.restart.on.unhealthy: "true"
    restart: "unless-stopped"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "8085:8085"
    environment:
      PORT: "8085"
      OLLAMA_API_BASE_URL: "http://192.168.100.9:11434/api"
      ENV: "production"
      WEBUI_AUTH: "false"
      WEBUI_NAME: "YAN AI"
      WEBUI_URL: "http://localhost:8085"
      WEBUI_SECRET_KEY: "yamiannephilim"
    networks:
      - yan
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama
    labels:
      deunhealth.restart.on.unhealthy: "true"
    restart: "unless-stopped"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "false"
      WATCHTOWER_TIMEOUT: "30s"
      WATCHTOWER_SCHEDULE: "0 * * * * *"
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_HTTP_API_TOKEN:-}
    networks:
      - yan
    labels:
      deunhealth.restart.on.unhealthy: "true"
    restart: "unless-stopped"

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:9999"
    environment:
      LOG_LEVEL: "info"
      HEALTH_SERVER_ADDRESS: "127.0.0.1:9999"
      TZ: "Asia/Ho_Chi_Minh"
    networks:
      - yan
    network_mode: "none"
    restart: "unless-stopped"

volumes:
  ollama: {}
  open-webui: {}

networks:
  yan:
    driver: bridge
